// Generated by evoke check; do not edit.

export interface Args {
  /** The whole screen, a window, or a selection? */
  area?: "screen" | "window" | "selection"
  /** To the clipboard instead of a file? */
  clipboard?: true
}

export interface Config {}

/** What the body receives beside its arguments. */
export interface Context {
  /** The input as it was typed. */
  input: string
  config: Config
  /** Aborted at the deadline or on a decline: stop, never guess. */
  signal: AbortSignal
}

/** What the body returns: the text a person reads, and data an app may use. */
export type Result = string | { text: string; data?: unknown }

/** The body: the default export of the file `run` names. */
export type Reflex = (args: Args, context: Context) => Result | Promise<Result>
